services:
  - type: web
    name: online-job-portal-milan-das
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: "true"
